name: VK Dating Bot

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Получить код
        uses: actions/checkout@v4

      - name: Установить Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Установить зависимости
        run: pip install -r requirements.txt

      - name: Запустить бота
        env:
          VK_TOKEN: ${{ secrets.VK_TOKEN }}
        run: python bot.py
